#!/usr/bin/bash

# Create virtual environment
if [ ! -d "venv" ]
then
  python3 -m venv .venv
fi

# Activate virtual environment
if [[ "$VIRTUAL_ENV" == "" ]]
then
  source .venv/bin/activate
fi

# Update virtual environment
python3 -m pip install -U pip setuptools wheel

# Install dependencies
pip install -r requirements-dev.txt

# Install pre-commit
pre-commit install

# Create .env from example
if [ ! -f .env ]
then
    copy .env.example .env
fi

# Delete the existing database
if [ -f db.sqlite3 ]
then
    rm -f db.sqlite3
fi

# Initialize a clean database
alembic -c app/migrations/alembic.ini revision --autogenerate
alembic -c app/migrations/alembic.ini upgrade head

# Create super user
flask user admin user pass
